language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
os:
  - linux
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt -f install
  - sudo apt-get install libsdl2-dev

stages:
  - format
  - build
  - test

jobs:
  include:
    - stage: format
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt
    - stage: build
      name: buildlinux
      os: linux
      script:
        - cargo build --bin start
        - cargo build --bin helloworld
    - stage: test
      script:
        - cargo test